### ISSUE TITLE
mach-o, but not built for iOSMac

### ISSUE THREAD

**Issue by tiferrei** [zhuowei/MarzipanTool#3]
I was able to build the app, however it depends on a couple of `Carthage` backed frameworks. When I try to launch the executable I get:
```
dyld: Library not loaded: @rpath/UCLKit.framework/UCLKit
  Referenced from: /Users/tiferrei/Library/Developer/Xcode/DerivedData/APIBuddy-bvqcebscaljzwkdnrmlnfebxizli/Build/Products/Debug-iphonesimulator/APIBuddy macOS.app/APIBuddy macOS
  Reason: no suitable image found.  Did find:
        /Users/tiferrei/Library/Developer/Xcode/DerivedData/APIBuddy-bvqcebscaljzwkdnrmlnfebxizli/Build/Products/Debug-iphonesimulator/APIBuddy macOS.app/Frameworks/UCLKit.framework/UCLKit: mach-o, but not built for iOSMac
[1]    15327 abort
```

I believe this might be due to either not using the correct platform version, although I've tried both macOS and iOS versions of the frameworks, or secondly, due to the way Carthage compiles the frameworks.

Any ideas?

**Comment by zhuowei** [comment]
@tiferrei You need to make sure all the libraries has the -fuse-ld flag applied when compiling and linking.

(the other approaches work around this by building normal non-iOSMac macOS executables instead, so you could try those if it doesn't work)

**Comment by tiferrei** [comment]
@zhuowei gotcha, thanks.
